DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS transaccion;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE PRODUCTO(
IDPRODUCTO INT NOT NULL AUTO_INCREMENT,
CODIGO INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(255) NOT NULL,
CANTIDAD INT NOT NULL,
PRECIO FLOAT NOT NULL,
PRIMARY KEY(IDPRODUCTO)
);

CREATE TABLE CLIENTE(
IDCLIENTE INT NOT NULL AUTO_INCREMENT,
DNI INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR(100) NOT NULL,
FECHANACIMIENTO DATE NOT NULL,
PRIMARY KEY(IDCLIENTE)
);

create table transaccion (
transaccionid int not null auto_increment,
fecha datetime,
monto float not null,
clienteid int,
primary key (transaccionid),
constraint FK_CLIENTE foreign key(clienteid)
references CLIENTE(IDCLIENTE)
);